name = "Janus"
uuid = "6d29d9de-a17f-4a34-97ae-711e7d293190"
version = "1.0.0-DEV"
authors = ["Jarvist Moore Frost <jarvist@gmail.com> and contributors"]

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
DelimitedFiles = "1.9.1"
LinearAlgebra = "1.12.0"
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
