name = "Janus"
uuid = "6d29d9de-a17f-4a34-97ae-711e7d293190"
authors = ["Jarvist Moore Frost <jarvist@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
